### PR TITLE
fix data race in gossipsub piggybacking

### LINKED ISSUE #98: Data race in gossipsub piggybacking
`GossipSubRouter.sendRPC` calls `gs.piggybackGossip` on a shared RPC object. It should probably copy it first.

### PR DESCRIPTION
**Pull request by vyzo**
Fixes data race in ownership of RPC when piggybacking control messages.
Closes #98

### CODE REVIEW

**Comment by vyzo** [comment]
We should probably gx publish and bubble up this one to ipfs, it's a nasty bug.

File: comm.go [hunk 1]
```diff
@@ -122,3 +122,22 @@ func rpcWithControl(msgs []*pb.Message,
 		},
 	}
 }
+
+func copyRPC(rpc *RPC) *RPC {
+	res := &RPC{
```
Comment (Stebalien) [inline comm.go]:
```go
res := new(RPC)
*res = *rpc
if rpc.Control != nil {
    *res.Control = *rpc.Control
}
```

**Review by Stebalien — COMMENTED** [review]
Does it really cost *that* much to create a new RPC per peer?

File: comm.go (hunk 1 above)
Comment (vyzo) [reply comm.go]: Hrm, we still need to create the control object -- it's a pointer.

Comment (vyzo) [reply comm.go]: But still, more idiomatic and terse.

**Comment by vyzo** [comment]
No, it doesn't cost all that much if it is to fix a bug :)

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
> Does it really cost that much to create a new RPC per peer?

My point was that we could create a new one per peer in `Publish`, if that's the only real issue. But we can change that later.
