### PR TITLE
Fix close of closed channel

### LINKED ISSUE #425: panic: close of closed channel
Reported https://github.com/prysmaticlabs/prysm/issues/8958.

```
May 29 13:45:06 prysm prysm.sh[2728527]: panic: close of closed channel
May 29 13:45:06 prysm prysm.sh[2728527]: goroutine 210 [running]:
May 29 13:45:06 prysm prysm.sh[2728527]: github.com/libp2p/go-libp2p-pubsub.(*Subscription).close(...)
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/subscription.go:46
May 29 13:45:06 prysm prysm.sh[2728527]: github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleRemoveSubscription(0xc0002c2c00, 0xc061f75700)
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/pubsub.go:674 +0xa5
May 29 13:45:06 prysm prysm.sh[2728527]: github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc0002c2c00, 0x1e31910, 0xc00037f2c0)
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/pubsub.go:558 +0x1505
May 29 13:45:06 prysm prysm.sh[2728527]: created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/pubsub.go:293 +0xb7e
```

I'm not sure how to reproduce this issue, but this routine seems to close a chan that is already closed.

https://github.com/libp2p/go-libp2p-pubsub/blob/v0.4.0/subscription.go#L45-L47

```
github.com/libp2p/go-libp2p-pubsub v0.4.0
```

### PR DESCRIPTION
**Pull request by gammazero**
This happens when there are multiple subscriptions to a topic and a single subscription is canceled twice.

FIxes #425

### CODE REVIEW

File: subscription.go [hunk 1]
```diff
@@ -43,5 +44,8 @@ func (sub *Subscription) Cancel() {
 }
 
 func (sub *Subscription) close() {
-	close(sub.ch)
+	if !sub.closed {
+		close(sub.ch)
+		sub.closed = true
+	}
```
Comment (vyzo) [inline subscription.go]: this needs to be atomic or we can have two concurrent closes fail; can you make this an swap/compare with an atomic variable?

**Review by vyzo — CHANGES_REQUESTED** [review]

File: subscription.go (hunk 1 above)
Comment (gammazero) [reply subscription.go]: Looked like close is never called concurrently; only called by the handler goroutine. ...but in case it is someday...

**Review by vyzo — APPROVED** [review]

**Comment by vyzo** [comment]
thank you!
